version: 2.2.7.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2019
configuration: Release
platform: Any CPU
force_https_clone: true
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST: https://www.myget.org/F/wannasport
  NUGET_APIKEY: 
    secure: TtqPjFwlqNLg0X2F4D5bDrHC8vDM0QFtHkjsKPKkBWeUl8zk3UMQdeweosJ6zu47
build: off
build_script:
- ps: >-
    dotnet build .\HungarianAlgorithm.sln;
test: off
test_script:
- ps: >-
    dotnet test .\.tests\HungarianAlgorithm.Test\HungarianAlgorithm.Test.csproj
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
- path: '**\*.snupkg'
  name: NuGet Symbol Package
deploy:
- provider: NuGet
  server: $(NUGET_HOST)
  api_key: $(NUGET_APIKEY)
  on:
    branch: master
